### ISSUE TITLE
[1주차] SELECT(기초)

### ISSUE THREAD

**Issue by shchooii** [Endless-Creation-33rd/MySQL_Study#1]
1주차 필수 문제
- [x] [모든 레코드 조회하기](https://school.programmers.co.kr/learn/courses/30/lessons/59034)
- [x] [역순 정렬하기](https://school.programmers.co.kr/learn/courses/30/lessons/59035)
- [x] [아픈 동물 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/59036)
- [x] [어린 동물 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/59037)
- [x] [여러 기준으로 정렬하기](https://programmers.co.kr/learn/courses/30/lessons/59404)
- [x] [상위 n개 레코드](https://school.programmers.co.kr/learn/courses/30/lessons/59405)

**Comment by sweetburble** [comment]
> 1주차 필수 문제
> 
> * [x]  [모든 레코드 조회하기](https://school.programmers.co.kr/learn/courses/30/lessons/59034)
> * [x]  [역순 정렬하기](https://school.programmers.co.kr/learn/courses/30/lessons/59035)
> * [x]  [아픈 동물 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/59036)
> * [x]  [어린 동물 찾기](https://school.programmers.co.kr/learn/courses/30/lessons/59037)
> * [x]  [여러 기준으로 정렬하기](https://programmers.co.kr/learn/courses/30/lessons/59404)
> * [x]  [상위 n개 레코드](https://school.programmers.co.kr/learn/courses/30/lessons/59405)

**Comment by shchooii** [comment]
수고하셨습니다~~
