### ISSUE TITLE
[2주차] SUM, MAX, MIN

### ISSUE THREAD

**Issue by shchooii** [Endless-Creation-33rd/MySQL_Study#2]
2주차 필수 문제
- [x] [가격이 제일 비싼 식품의 정보 출력하기](https://school.programmers.co.kr/learn/courses/30/lessons/131115)
- [x] [가장 비싼 상품 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/131697)
- [x] [최댓값 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/59415)
- [x] [최솟값 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/59038)
- [x] [동물 수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/59406)
- [x] [중복 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/59408)

많이 쉽죠?.... GROUP BY 부터 어려워질 거에요. 가볍게 풀어주세요~~

**Comment by sweetburble** [comment]
2주차 필수 문제
- [x] [가격이 제일 비싼 식품의 정보 출력하기](https://school.programmers.co.kr/learn/courses/30/lessons/131115)
- [x] [가장 비싼 상품 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/131697)
- [x] [최댓값 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/59415)
- [x] [최솟값 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/59038)
- [x] [동물 수 구하기](https://school.programmers.co.kr/learn/courses/30/lessons/59406)
- [x] [중복 제거하기](https://school.programmers.co.kr/learn/courses/30/lessons/59408)

ㅋㅋㅋ
